### ISSUE TITLE
Noise at sites

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#16]
Denis has raised this issue in emails (in the context of overlapping runs). 

We need an analysis of the underlying noise in the system. The noise variable may provide us with that. Other statistics that could be computed, across any set of receivers. The interval would likely be time specific (that is, not related to runID or batchID) because not all noisy receivers are noisy all the time. 

Indicators of noise would be overlapping runs of the same tag, many tags from different projects in the same interval, a very high (how high?) proportion of runLen 2, 3, 4, possibly others. 

A first step would be compute these statistics (and others) for known noisy and quite receivers, and examine the relationship between the statistics and the internal 'noise' variable.

If the internal noise variable is informative, then we can provide guidelines to users about how to filter sites/times based on noise. If another statistic adds value, then we should add it as a variable accessible to users through the alltags view (because they could not compute it themselves). 

We should identify extreme cases of noise, and mask those data (or implement a special query to get them). We should also identify these sites to their owners, and help them fix them.

**Comment by StuMackenzie** [comment]
A good starting point may be with the following receivers. These are the noisiest that I'm aware of, although there are many others. The patterns of noise at each of these is also quite different. Koffler is sporadic, Formosa was nearly constant, and Old Cut is also sporadic, but in distinct bursts/pulses where numerous tags are detected all at the same time - some source of interference that only happens at certain times for one reason or another.

Personally, I think we should delete all of the data from the Formosa deployments. Unfortunately, Koffler has some good stuff mixed in, and we can't get rid of Old Cut data because it probably has the most detections of any station in the system.

Koffler - SG-3214BBBK6103, Deployment 2729
Formosa - SG-3615BBBK1E34. Deployments 3071, 3742, 3984
Old Cut - SG-5113BBBK2972

**Comment by zcrysler** [comment]
Closed and moved here: https://github.com/MotusDev/Filtering-Noisy-Sites/issues/1
