### ISSUE TITLE
applyRunsFilter returns a dataframe

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#2]
The only (?) way to apply a runs filter returns a data frame, which complicates the workflow for large databases.

**Comment by denislepage** [comment]
It doesn't defeat the purpose of storing the filter in sql, since the dataframe returned is extracted based on a sql query from alltags. Doing the same with an R merge would require extracting the full dataset first, which this approach avoids.

    return (sqlq("select * from (select a.*, (SELECT probability from runsFilters b where a.runID = 
        b.runID and a.motusTagID = b.motusTagID and filterID = %d) as probability from alltags a) tbl where IFNULL(probability,1) >= %f %s", 
        filterID, p.min, where.stmt))

That said, if you prefer to have a dplyr::tbl object returned, it should be easily done by modifying the returned object. I was under the impression that most of the operations/functions that Zoe had created were based on a dataframe, but it may have changed.

I can make the change and test it a bit if you all think this is a better way.

    return dplry::tbl(src, sql("select * from (select a.*, (SELECT probability from runsFilters b where a.runID = 
        b.runID and a.motusTagID = b.motusTagID and filterID = %d) as probability from alltags a) tbl where IFNULL(probability,1) >= %f %s", 
        filterID, p.min, where.stmt))

**Comment by tabanid** [comment]
The issue is that it is often not possible (or very slow) to load huge data frames in R. 

A typical workflow (from the book) operates first on the sql file (filtering and selecting variables, subsetting and so on) before converting to a data frame. 

The applyRunsFilter bypasses the initial steps, and just delivers a filtered dataframe ... is there a way to do otherwise?

What I'd like to see is the ability to add a variable to the alltags view that was for a particular filter (or multiple filters). That could then be converted to a data frame downstream. 

Doing it that way allows for simple filtering using the dplyr filter function, and also allows the user to view the effects of different filters (graphically or otherwise). If it isn't possible to do it that way, then I think we revert to showing people that workflow (which is simple).

**Comment by tcrewe** [comment]
I agree with Phil's suggestion on this.  The applyRunsFilter would add a
variable to the alltags view, and users could simply filter using the dplyr
functions (as opposed to the p.min statement). In fact, you could
potentially just have the writeRunsFilter add the probabilities to the
alltags view, and drop one step of the 3-step filtering process?

**Comment by denislepage** [comment]
If the function returned an dplyr object instead of a dataframe, as per my previous note, can you not use dplyr to merge it with another dplyr object to add additional fields? I’m not familiar enough with the syntax, but I think it’s possible.

The apply tags filter doesn’t do very much, so you can also create your own code with customized fields if you want. You don’t have to use the function to apply a filter. The sql syntax is a bit unwieldy for someone unfamiliar with sql, but that’s how I best know how to do it. You might be able to achieve the same entirely with dplyr syntax.

Note that the function already adds the probability from your selected filter to the list of fields in alltags. What other fields do you mean to add?

I’d need to understand more precisely what you are interested in doing to suggest a solution.

**Comment by tcrewe** [comment]
So when you use writeRunsFilter, the probabilities are already attached to
the alltags view?  So after running writeRunsFilter, can I simply use
tbl(sql.motus, "alltags"), and this will output a sql table with the
probabilities attached?

**Comment by denislepage** [comment]
I have modified the staging branch to have the function return a tbl object instead of a dataframe. I haven't tested it yet.
