### ISSUE TITLE
Revisions to book

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#22]
We need to discuss how we are going to do revisions to the book. For each of the following we need to assign someone, and then we need to agree on how/what/when we do things. 

I think we need at least the following:

1. simple corrections of errors and updates -- these should be done regularly, as noticed. Who is in charge of doing this?
2. collating issues that users face
 a) issues understanding the text in the book
 b) issues that are coming up that aren't covered in the book. 
3. Enhancements and alternate workflows.

**Comment by StuMackenzie** [comment]
Notes from Zoe: 19 January:
Along with the notice, it might be a good time to revisit the public error log we made on github: https://github.com/MotusWTS/Motus-Public-Error-Log

If we want users to start using this to report issues we should tell them about it and create clear instructions – are we ready to do this?  If so we should clarify what exactly should be reported here.  Right now the description is ”Public repository for bugs and issue reporting to the tag and receiver metadata database.” But we could use it for user reported missing data if they report specified details, along with errors in the tagme() function etc.  This would help clear out my inbox and make it easier for me to manage missing data questions since it’s difficult for me to pinpoint where the issue lies.  It would also be useful for users because they could just check back on their report to see what progress has been made, rather than sending multiple emails asking on updates that I’m also waiting on.

There are a few missing data issues:
-	Uploads don’t appear to go through: I can easily check if their upload exists in the system
-	Uploads appear to be processed but data doesn’t show up in John’s hourly plots: I get stuck at logging the error with John and can’t provide useful feedback to users
-	Uploads appear to be processed and in John’s hourly plots but don’t end up in .motus files: end up having to go through one of you to sort it out
-	Probably others

We would need to commit to checking this and using it to report back to users, I’d be happy to manage it and assign people as needed if everyone agrees we can make it public

**Comment by StuMackenzie** [comment]
Reply from Denis. 19 January

If we knew what we wanted to get out of them, a feedback form with specific fields might help ensure that they provide everything we need?

I’m concerned that a github issue tracker isn’t the best way to get that sort of feedback from most users. It’s useful for us internally, but people would have to create a github account, and I am not sure they’d be more precise than sending an email. If we want specific details, why not ask for them directly? Java errors also generate a reference number (a timestamp). On the error page, we could also offer a link to the error report page, and reference the error number, so we can link it to the email received.

We could ask some questions like:

1.	please identify the type of issue you are reporting:
a.	Missing data in R package
b.	Motus web site error
c.	File upload error
2.	Please provide specific details where applicable
a.	Motus Project: 
b.	Motus tags: 
c.	Receivers:
d.	Are you using your own Motus login when the error occurs?
e.	Web page where the error occurs:
3.	Please describe the steps that lead to the error, including a sample R script if appropriate

**Comment by tcrewe** [comment]
I think Phil’s suggestion is more specific to the book, lack of clarity, other things to include, etc.

This additional string from Zoe/Denis is more to do with data issues. Equally important, but we probably don’t want to deal with both in the same way, or at least we need different places to report errors/suggestions for book vs data management.

We will be discussing today, from the looks of the agenda?

Tara

**Comment by tcrewe** [comment]
Currently stands as Zoe to post issues from users to GIT, Tara will check, fix and push 1/week. Quick changes made to Master branch, merge to beta. Bigger changes (new chapters, etc), add to beta branch, and these will be released to Master with version release.
