### ISSUE TITLE
tagDeps table names

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#3]
In the tagDeps table, there is a variable 'tagID'. Is this the same as motusTagID in the 'alltags' view? Should they not be the same for consistency?

**Comment by denislepage** [comment]
Changing the table field names is somewhat more complicated and potentially disruptive than changing the view field names. 1) The R package earlier than the switch would no longer work. 2) the files loaded before the switch would need to be modified (requires creating a copy of the entire table to be modified, transferring all data into it, and deleting the original one). Because some of the steps are currently spread across 2 packages (ensureDBTable in motusClient and updateMotusDb in motus), this further complicates the process if both packages are not updated at the same time.

Plus, unless we made significant changes to the API, we can't currently support 2 different suite of field names for different versions of a package.

All in all, I agree this is annoying, but I am pretty sure it is not worth the troubles.

A much easier approach would be to create new views that have the sole purpose of making the names consistent with those used in alltags.

**Comment by tabanid** [comment]
Ok (with the views, if that is easy). I think we need to leave alltags as is, but perhaps could modify the others? How many would need to be fixed?

**Comment by denislepage** [comment]
There are no views at the moment except alltags and allambigs (which is for internal use). So, we are looking at creating new ones.

We could make a view that combines tags and tagDeps and one that combines receiver details.

I’m not sure what else you would need.

**Comment by tabanid** [comment]
Resolved on phone call. It was also noted that tag deployment information is now present in the alltags view, so these merges with the tag deployment data can be removed from the book. As Denis notes, the issue can be most easily resolved by creating a new view (if we need to).
