### ISSUE TITLE
Some sample data receivers are missing deployment information

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#5]
See below. 

BBK0382 and BBK0698 are trivial. 

BBK0547 is over a longer period. 

I'll deal with the missing receiver info in another issue. 

> ## some receivers in sample data are missing information
> df.nolatlon <- filter(df.alltags, is.na(recvLat)) %>% select(recv, ts, recvDeployName, recvProjName, 
+                                               recvDeployLat, recvDeployLon, gpsLat, gpsLon, 
+                                               recvLon, recvAlt) %>% 
+   group_by(recv, gpsLat, gpsLon, recvDeployLat, recvDeployLon) %>%
+   summarize(min.ts = min(ts), 
+             max.ts = max(ts))
> df.nolatlon
# A tibble: 5 x 7
# Groups: recv, gpsLat, gpsLon, recvDeployLat [?]
  recv            gpsLat gpsLon recvDeployLat recvDeployLon min.ts              max.ts             
  <chr>            <dbl>  <dbl>         <dbl>         <dbl> <dttm>              <dttm>             
1 SG-1415BBBK0382     NA     NA            NA            NA 2015-09-12 08:40:34 2015-09-12 08:41:29
2 SG-2814BBBK0547     NA     NA            NA            NA 2015-08-18 14:47:10 2015-10-20 06:24:52
3 SG-3115BBBK0698     NA     NA            NA            NA 2017-03-10 00:35:34 2017-03-10 00:35:34
4 NA                   0      0            NA            NA 2015-10-26 11:27:54 2015-10-26 12:41:29
5 NA                  NA     NA            NA            NA 2015-08-17 17:01:38 2015-10-26 11:30:49
>

**Comment by cjardine-bsc** [comment]
There wasn't any data missing from sample_r_metadata_for_receivers_recvdeps. This was a complete copy of all deployments when it was created. (max deployID = 4446). 

The serial number you reference above (SG-2814BBBK0547) had a new deployment created since I copied data to the sample tables (deployID 4476) which is why it's missing a deployment in the sample data. 

As for the other two, there is receiver deployment data in the .motus file for 176 if you look in recvDeps, but, the all tags view isn't joining to those records since they fall outside the deployments. 

LEFT JOIN recvDeps AS t6 ON t6.deviceID = t3.motusDeviceID 
							AND t6.tsStart = (SELECT max(t6b.tsStart) 
											  FROM recvDeps AS t6b 
											  WHERE t6b.deviceID=t3.motusDeviceID 
											  AND t6b.tsStart <= t1.ts 
											  AND (t6b.tsEnd IS NULL OR t6b.tsEnd >= t1.ts) ) 

For example, the only deployment for SG-1415BBBK0382 starts in 2016, which is why the hits you list above are not getting assigned to this deployment, they are from 2015. 

SG-1415BBBK0382 NA NA NA NA 2015-09-12 08:40:34 2015-09-12 08:41:29

The deployment in the .motus file for this receiver is the only deployment in the DB for this receiver.

As far as I can tell these missing lat/longs all seem to be cases of bad metadata, not problems in the sample data tables or the API. Updating the sample data tables with the 8 new deployments (effecting this project) that have been created since I pulled the sample data would address some of these issues, but since we want bad metadata instances to exist in the sample data for Zoe and Tara to work with, I've opted to leave this alone for now.
