### ISSUE TITLE
Some receivers in the sample data do not have names.

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#6]
Some of these have lat/lons, others don't. 

```
 ## do any of those have info outside of the deployment period?
> df.outside <- filter(df.alltags, recv %in% df.nolatlon$recv) %>%
+   select(recv, ts, recvDeployName, recvProjName, 
+          recvDeployLat, recvDeployLon, gpsLat, gpsLon, 
+          recvLon, recvAlt) %>%
+   group_by(recv, gpsLat, gpsLon)  %>%
+   summarize(min.ts = min(ts), 
+             max.ts = max(ts), 
+             n.detect = length(ts))
> df.outside
# A tibble: 56 x 6
# Groups: recv, gpsLat [?]
   recv            gpsLat gpsLon min.ts              max.ts              n.detect
   <chr>            <dbl>  <dbl> <dttm>              <dttm>                 <int>
 1 SG-1415BBBK0382  NA      NA   2015-09-12 08:40:34 2015-09-12 08:41:29       18
 2 SG-2814BBBK0547  51.2   -79.8 2016-10-09 23:52:45 2016-10-10 00:00:42      172
 3 SG-2814BBBK0547  NA      NA   2015-08-18 14:47:10 2015-10-20 06:24:52      117
 4 SG-3115BBBK0698  NA      NA   2017-03-10 00:35:34 2017-03-10 00:36:33        4
 5 NA              -42.5   -73.8 2017-02-24 16:42:41 2017-03-12 06:23:08      131
 6 NA              -42.5   -73.8 2017-02-24 00:09:04 2017-03-28 07:06:38      298
 7 NA              -42.5   -73.8 2017-02-24 06:11:46 2017-03-11 05:21:56       17
 8 NA              -42.5   -73.8 2017-03-03 09:52:22 2017-03-21 12:57:46       29
 9 NA                0       0   2015-10-26 11:27:54 2015-10-26 12:41:29       56
10 NA                9.02  -79.4 2016-12-11 17:29:03 2016-12-11 17:30:14        2
# ... with 46 more rows
> 
```

**Comment by denislepage** [comment]
Isn't this the same issue as #5 ? The receivers don't have names per say. Only deployments have. I thought the point of having the sample data was to show the types of problems that you mention here, and explain how people can deal with incomplete data. If you want the sample data to be free of these types of problems, we can remove data that don't match deployments from the sample, but this was not the original intent.

**Comment by tcrewe** [comment]
The original intent was to show how to find some of these types of errors
(lat/lon), but some time ago (several months now), we decided the metadata
chapter would become a deployment chapter, to show people where their
deployments were, how many were detected, etc. This was primarily because
the message center was going to highlight errors, which should be fixed
behind the scenes.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-7272190102947337488_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by cjardine-bsc** [comment]
See my comment on the below issue and let me know if you'd like me to update the metadata for sample data based on changes users have made recently. 

https://github.com/MotusWTS/MotusRBook/issues/5#event-1438460684

**Comment by tabanid** [comment]
I think this has largely been fixed in various other places.
